export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const PROJECT_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID!;
export const ENDPOINT = process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT!;
export const BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_BUCKET_ID!
export const PROJECT_NAME = process.env.NEXT_PUBLIC_APPWRITE_PROJECT_NAME!;
export const EXTRACT_ROOMS_TABLE_ID= process.env.NEXT_PUBLIC_APPWRITE_EXTRACT_ROOMS_TABLE_ID!
export const AI_EXTRACT_ROOMS_TABLE_ID= process.env.NEXT_PUBLIC_APPWRITE_AI_EXTRACT_ROOMS_TABLE_ID!